version: '3.8'

services:
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hambre
    ports:
      - "3306:3306"

  flask_app:
    container_name: flask_app
    build:
      context: .
      dockerfile: Dockerfile
    # restart: always
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - mariadb
